---
- link: https://boardgamegeek.com/boardgame/85036
  name: 20th Century (2010)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/38359
  name: The 3 Commandments (2008)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/249039
  name: 5 Minute Chase (2018)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/175878
  name: 504 (2015)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/68448
  name: 7 Wonders (2010)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/173346
  name: 7 Wonders Duel (2015)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/172818
  name: Above and Below (2015)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/31260
  name: Agricola (2007)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/6249
  name: Alhambra (2003)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/74
  name: Apples to Apples (1999)
  stars: 1.0
- link: https://boardgamegeek.com/boardgame/31449
  name: Army of Frogs (2007)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/145633
  name: 'Ascension: Apprentice Edition (2013)'
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/65200
  name: Asteroyds (2010)
  stars: 3.0
- link: https://boardgamegeek.com/boardgame/180680
  name: Automobiles (2016)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/95589
  name: Bad Grandmas (2011)
  stars: 3.0
- link: https://boardgamegeek.com/boardgame/182094
  name: BANG! The Duel (2015)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/160567
  name: 'BANG!: The Walking Dead (2014)'
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/216640
  name: The Banishing (2017)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/219513
  name: Bärenpark (2017)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/211534
  name: Bears vs Babies (2017)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/245710
  name: Blossoms (2018)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/11
  name: Bohnanza (1997)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/131835
  name: 'Boss Monster: The Dungeon Building Card Game (2013)'
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/206803
  name: Capital (2016)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/822
  name: Carcassonne (2000)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/12902
  name: 'Carcassonne: The City (2004)'
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/191041
  name: Carrotia (2016)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/84876
  name: The Castles of Burgundy (2011)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/13
  name: Catan (1995)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/18602
  name: Caylus (2005)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/209685
  name: 'Century: Spice Road (2017)'
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/193212
  name: Chariot Race (2016)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/554
  name: La Città (2000)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/178900
  name: Codenames (2015)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/198773
  name: 'Codenames: Pictures (2016)'
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/118174
  name: Compounded (2013)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/143986
  name: CV (2013)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/181494
  name: CVlizations (2015)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/202977
  name: 'Cytosis: A Cell Biology Board Game (2017)'
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/207370
  name: Design Town (2016)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/101
  name: Detroit-Cleveland Grand Prix (1996)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/157322
  name: Dice Brewing (2014)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/218121
  name: Dice Hospital (2018)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/122313
  name: The Doge Ship (2012)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/36218
  name: Dominion (2008)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/40834
  name: 'Dominion: Intrigue (2009)'
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/9408
  name: Dos Rios (2004)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/194880
  name: Dream Home (2016)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/193483
  name: Dwar7s Fall (2016)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/1460
  name: Earthquake (1998)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/175621
  name: Epic Card Game (2015)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/163976
  name: Exoplanets (2015)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/172225
  name: Exploding Kittens (2015)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/172242
  name: 'Exploding Kittens: NSFW Deck (2015)'
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/138161
  name: 'Firefly: The Game (2013)'
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/84469
  name: Fürstenfeld (2010)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/163081
  name: Galaxy of Trian (2014)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/31481
  name: Galaxy Trucker (2007)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/129293
  name: Gauntlet of Fools (2012)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/134157
  name: Guilds of London (2016)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/116
  name: Guillotine (1998)
  stars: 3.0
- link: https://boardgamegeek.com/boardgame/57925
  name: Havana (2009)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/2655
  name: Hive (2001)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/119265
  name: Hospital Rush (2014)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/154203
  name: Imperial Settlers (2014)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/230342
  name: InBetween (2017)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/66076
  name: Industry (2010)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/2989
  name: Instinct (1998)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/153238
  name: Ivor the Engine (2014)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/70323
  name: King of Tokyo (2011)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/107529
  name: Kingdom Builder (2011)
  stars: 3.0
- link: https://boardgamegeek.com/boardgame/85325
  name: Kolejka (2011)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/201502
  name: Korporacja (2015)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/463
  name: 'Magic: The Gathering (1993)'
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/31075
  name: Ming Dynasty (2007)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/147624
  name: Mount Everest (2013)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/192638
  name: Multiuniversum (2016)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/86955
  name: Munchkin Zombies (2011)
  stars: 2.0
- link: https://boardgamegeek.com/boardgame/163413
  name: Murano (2014)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/191438
  name: North American Railways (2016)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/194879
  name: Not Alone (2016)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/234277
  name: Nusfjord (2017)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/183840
  name: Oh My Goods! (2015)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/127095
  name: Origin (2013)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/15318
  name: Palazzo (2005)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/30549
  name: Pandemic (2008)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/161936
  name: 'Pandemic Legacy: Season 1 (2015)'
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/221107
  name: 'Pandemic Legacy: Season 2 (2017)'
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/75358
  name: Paris Connection (2010)
  stars: 3.0
- link: https://boardgamegeek.com/boardgame/163412
  name: Patchwork (2014)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/223779
  name: Pocket Mars (2017)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/2651
  name: Power Grid (2004)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/3076
  name: Puerto Rico (2002)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/109764
  name: Quarantine (2013)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/28143
  name: Race for the Galaxy (2007)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/6617
  name: Rapidough (1994)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/128882
  name: 'The Resistance: Avalon (2012)'
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/220926
  name: 'Rick and Morty: Anatomy Park – The Game (2017)'
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/246534
  name: 'Rick and Morty: The Rickshank Rickdemption Deck-Building Game (2018)'
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/121921
  name: 'Robinson Crusoe: Adventures on the Cursed Island (2012)'
  stars: 2.5
- link: https://boardgamegeek.com/boardgame/199561
  name: Sagrada (2017)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/29599
  name: Scandaroon (2007)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/230266
  name: Scare It! (2018)
  stars: 3.0
- link: https://boardgamegeek.com/boardgame/148261
  name: SeaFall (2016)
  stars: 3.0
- link: https://boardgamegeek.com/boardgame/97786
  name: Small World Underground (2011)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/119432
  name: Snowdonia (2012)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/148228
  name: Splendor (2014)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/145400
  name: Strajk! Skok do wolności (2013)
  stars: 3.0
- link: https://boardgamegeek.com/boardgame/206156
  name: 'SUPERHOT: The Card Game (2017)'
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/1111
  name: Taboo (1989)
  stars: 2.5
- link: https://boardgamegeek.com/boardgame/475
  name: Taj Mahal (2000)
  stars: 0.0
- link: https://boardgamegeek.com/boardgame/186323
  name: Tavarua (2016)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/120677
  name: Terra Mystica (2012)
  stars: 4.5
- link: https://boardgamegeek.com/boardgame/217085
  name: Unearth (2017)
  stars: 4.0
- link: https://boardgamegeek.com/boardgame/180845
  name: Wibbell++ (2017)
  stars: 3.5
- link: https://boardgamegeek.com/boardgame/266192
  name: Wingspan (2019)
  stars: 5.0
- link: https://boardgamegeek.com/boardgame/29387
  name: Zombie Fluxx (2007)
  stars: 3.0
